apiVersion: apps/v1
kind: Deployment
metadata:
  name: buysellguess-dep-helm
spec:
  replicas: 0
  selector:
    matchLabels:
      app: buysellguess
  template:
    metadata:
      labels:
        app: buysellguess
    spec:
      containers:
        - name: buysellguessapp
          image: ghcr.io/pwdelbloomboard/ps-container