apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: buysellguess-dep-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: buysellguess-dep
          servicePort: 2345